### ISSUE TITLE
Feature: Internal Logic

### ISSUE THREAD

**Issue by tristanchase** [tristanchase/gen-keys#2]
# Epic Title

Feature: Internal Logic

## Epic Description

This feature will fortify the internal logic of the gen-keys script by:

* Creating or appending to a `config` file
* Creating a `known_hosts` file for each key
* Maintaining a list of keys to be added by `keychain`
* Appending the public key to a remote host, if possible, or at least displaying it for copy/paste to a website (e.g. github.com)
* Giving the option for different encoding schemes and bit lengths

Ideas here https://dev.to/josephmidura/how-to-manage-multiple-ssh-key-pairs-1ik

## List of Tasks (Complete in order)

- [x] [Task 1: Create known_hosts file for each key](https://github.com/tristanchase/gen-keys/issues/3)
- [x] [Task 2: Establish config file logic](https://github.com/tristanchase/gen-keys/issues/4)
- [x] [Task 3: Give encoding options](https://github.com/tristanchase/gen-keys/issues/5)
- [x] [Task 4: Handle public key transfer](https://github.com/tristanchase/gen-keys/issues/6)
- [x] [Task 5: Maintain list of keys](https://github.com/tristanchase/gen-keys/issues/7)

[Feature: Internal Logic](https://github.com/tristanchase/gen-keys/issues/2)
